### ISSUE TITLE
Is it possible to provide k.mapping() during training?

### ISSUE THREAD

**Issue by Fil** [seracio/kohonen#42]
I'm just trying out this library (thanks for sharing!), and would like to create a demonstrator of the algorithm.

For this I would like to be able to "pause" every few steps and display the current state of the system. `log()` seems to get the state of the neurons only.

Here's a (very simple and unfinished) demo
http://bl.ocks.org/Fil/ae11126ae728cb2af627db6a3dfa756b

![](https://cloud.githubusercontent.com/assets/7001/18251849/e87b3584-738b-11e6-8c71-aac32b1028ab.png)

**Comment by hllwd** [comment]
That would be nice indeed! I think we can achieve this by overriding the training method or adding a trainingWithPause generator for instance... I'll give a try this week

```javascript
    training(log = () => {
    }) {
        for (let i = 0; i < this.maxStep; i++) {
            // generate a random vector
            this.learn(this.generateLearningVector());
            log(this.neurons, this.step);
        }
    }
```

**Comment by hllwd** [comment]
I close the issue, as you can add a generator in a subclass to achieve this
